# syntax=docker/dockerfile:1

# Get image for building App
FROM golang:1.21.3 AS builder

# Working directory
WORKDIR /app

# Copy source code
COPY go.mod go.sum ./

RUN go mod download

COPY ../../ .

# Build App
RUN CGO_ENABLED=0 GOOS=linux  go build -o api_tester

# Get lighter Linux image
FROM alpine:3.14

# Install tool wget and curl
RUN apk --no-cache add wget curl

# Copy exec in Linux folder
COPY --from=builder /app/api_tester /usr/local/bin/api_tester

# App entrypoint
CMD ["api_tester"]
